baseURL = "/"
title = "–ü–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

[params]
  description = "–ö–µ–π—Å—ã –∏ –ø–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
  author_name = "–†—É—Å–ª–∞–Ω"
  author_surname = "–®–∞—Ä–∏–ø–æ–≤"
  author_grade = "—Å—Ç–∞—Ä—à–∏–π –ø—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
  author_city = "–°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥"
  author_intro = "üëãüèª, —è –ø—Ä–æ–µ–∫—Ç–∏—Ä—É—é —Ü–∏—Ñ—Ä–æ–≤—ã–µ –ø—Ä–æ–¥—É–∫—Ç—ã —Å —É—á–µ—Ç–æ–º –±–æ–ª–µ–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∏ –±–∏–∑–Ω–µ—Å–∞."
  author_image = "images/author.jpg"
  author_email = "ruslanshgd@gmail.com"
  author_telegram = "https://t.me/rsgdru"
  author_linkedin = "https://www.linkedin.com/in/ruslan-sharipov/"
  author_dribbble = ""
  author_behance = "https://www.behance.net/ruslansh"
  author_cv = "https://drive.google.com/file/d/17-WqbIrYUbzBeoUAbawsEdOcYIFguWre/view?usp=sharing"

  [params.education]

  [params.career]


  [[params.career.items]]
    company = "–¢-–ë–∞–Ω–∫"
    role = "–°—Ç–∞—Ä—à–∏–π –ø—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "2023"
    end = "–ø–æ –Ω–∞—Å—Ç–æ—è—â–µ–µ –≤—Ä–µ–º—è"
    description = "–ü—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª –ø–ª–∞—Ç—Ñ–æ—Ä–º—É –∏–Ω—Ü–∏–¥–µ–Ω—Ç –º–µ–Ω–µ–¥–∂–º–µ–Ω—Ç–∞, –∞ —Å–µ–π—á–∞—Å —Ä–µ—á–µ–≤—É—é –∞–Ω–∞–ª–∏—Ç–∏–∫—É –¥–ª—è –ª—É—á—à–µ–≥–æ –±–∞–Ω–∫–∞."
    logo = "images/logos/—Ç-–±–∞–Ω–∫.png"

  [[params.career.items]]
    company = "–ú–æ–π–û—Ñ–∏—Å"
    role = "–°—Ç–∞—Ä—à–∏–π UX –¥–∏–∑–∞–π–Ω–µ—Ä"
    start = "–ú–∞–π 2023"
    end = "–û–∫—Ç—è–±—Ä—å 2023"
    description = "–ó–∞ –≤—Ä–µ–º—è –∏—Å–ø—ã—Ç–∞—Ç–µ–ª—å–Ω–æ–≥–æ —Å—Ä–æ–∫–∞ —É–¥–∞–ª–æ—Å—å:\n\n- ¬´–ú–æ–π–û—Ñ–∏—Å –¢–µ–∫—Å—Ç¬ª —Ä–∞–±–æ—Ç–∞–ª –Ω–∞–¥ —Å—Ü–µ–Ω–∞—Ä–∏—è–º–∏: ¬´–°—Ä–∞–≤–Ω–µ–Ω–∏–µ –¥–æ–∫—É–º–µ–Ω—Ç–æ–≤¬ª –∏ ¬´–ü–æ–¥–ø–∏—Å—å –∏ –Ω—É–º–µ—Ä–∞—Ü–∏—è –æ–±—ä–µ–∫—Ç–æ–≤¬ª.\n- –í ¬´–ú–æ–π–û—Ñ–∏—Å –¢–∞–±–ª–∏—Ü—ã¬ª —Å–ø—Ä–æ–µ–∫—Ç–∏—Ä–æ–≤–∞–ª —Å—Ü–µ–Ω–∞—Ä–∏–∏ –¥–ª—è –º–∞–∫—Ä–æ–∫–æ–º–∞–Ω–¥.\n- ¬´–ú–æ–π–û—Ñ–∏—Å –ü—Ä–µ–∑–µ–Ω—Ç–∞—Ü–∏–∏¬ª –≤–º–µ—Å—Ç–µ —Å –∫–æ–º–∞–Ω–¥–æ–π —Å–¥–µ–ª–∞–ª–∏ –∫–ª–∞—Å—Å–Ω–æ–µ –ø–µ—Ä–µ–∫–ª—é—á–µ–Ω–∏–µ –º–µ–∂–¥—É —Å–ª–∞–π–¥–æ–≤ üòÄ.\n- –ü—Ä–æ—Ü–µ—Å—Å–Ω—ã–µ –∞–∫—Ç–∏–≤–Ω–æ—Å—Ç–∏: –≤—ã—Ö–æ–¥–∏–ª –Ω–∞ –ø—Ä–æ–µ–∫—Ç–Ω–æ–≥–æ –º–µ–Ω–µ–¥–∂–µ—Ä–∞, –≥–µ–Ω–¥–∏—Ä–µ–∫—Ç–æ—Ä–∞, —Ä—É–∫–æ–≤–æ–¥–∏—Ç–µ–ª—è –º–∞—Ä–∫–µ—Ç–∏–Ω–≥–∞ —Å –ø—Ä–µ–∑–µ–Ω—Ç–∞—Ü–∏–µ–π –∏ –≤–∏–¥–µ–æ, –ø–æ–¥—Å–≤–µ—á–∏–≤–∞—è —Ç–æ—á–∫–∏ —Ä–æ—Å—Ç–∞ –¥–ª—è —Å–∞–π—Ç–∞, —Å –ø–æ—Å—á–∏—Ç–∞–Ω–Ω–æ–π —é–Ω–∏—Ç-—ç–∫–æ–Ω–æ–º–∏–∫–æ–π b2c.\n- –î–ª—è –∫–æ–º–∞–Ω–¥—ã: —Å–¥–µ–ª–∞–ª —Ä–∞—Å—á–µ—Ç, –ø—Ä–∏–æ—Ä–∏—Ç–µ–∑–∞—Ü–∏—é –∏ –¥—ç—à–±–æ—Ä–¥ —ç—Ñ—Ñ–µ–∫—Ç–∏–≤–Ω–æ—Å—Ç–∏ uikit (–≤ –¥–µ–Ω—å–≥–∞—Ö, –≤—Ä–µ–º–µ–Ω–∏), –∏ —Å–æ–∑–¥–∞–ª ui-kit –ø–æ–¥ 3 –¥–µ—Å–∫—Ç–æ–ø–Ω—ã—Ö —Ä–µ–¥–∞–∫—Ç–æ—Ä–∞."
    logo = "images/logos/–º–æ–π–æ—Ñ–∏—Å.png"
[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # optional later: tag = "tags"
