baseURL = "/"
title = "–ü–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

[params]
  description = "–ö–µ–π—Å—ã –∏ –ø–æ—Ä—Ç—Ñ–æ–ª–∏–æ"
  author_name = "–†—É—Å–ª–∞–Ω"
  author_surname = "–®–∞—Ä–∏–ø–æ–≤"
  author_grade = "—Å—Ç–∞—Ä—à–∏–π –ø—Ä–æ–¥—É–∫—Ç–æ–≤—ã–π –¥–∏–∑–∞–π–Ω–µ—Ä"
  author_city = "–°–∞–Ω–∫—Ç-–ü–µ—Ç–µ—Ä–±—É—Ä–≥"
  author_intro = "üëãüèª, —è –ø—Ä–æ–µ–∫—Ç–∏—Ä—É—é —Ü–∏—Ñ—Ä–æ–≤—ã–µ –ø—Ä–æ–¥—É–∫—Ç—ã —Å —É—á–µ—Ç–æ–º –±–æ–ª–µ–π –ø–æ–ª—å–∑–æ–≤–∞—Ç–µ–ª–µ–π –∏ –±–∏–∑–Ω–µ—Å–∞."
  author_image = "images/author.jpg"
  author_email = "ruslanshgd@gmail.com"
  author_telegram = "https://t.me/rsgdru"
  author_linkedin = "https://www.linkedin.com/in/ruslan-sharipov/"
  author_dribbble = ""
  author_behance = "https://www.behance.net/ruslansh"
  author_cv = "https://drive.google.com/file/d/17-WqbIrYUbzBeoUAbawsEdOcYIFguWre/view?usp=sharing"

  [params.education]

  [params.career]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
  # optional later: tag = "tags"
