baseURL = "/"
title = "Портфолио"
languageCode = "ru-ru"
defaultContentLanguage = "ru"

[params]
  description = "Кейсы и портфолио"
  author_name = ""
  author_surname = ""
  author_grade = ""
  author_city = ""
  author_intro = ""
  author_image = "images/author.jpg"
  author_email = ""
  author_telegram = ""
  author_linkedin = ""
  author_dribbble = ""
  author_behance = ""
  author_cv = ""

  [params.education]

  [params.career]

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML"]

[taxonomies]
